In [52]:
%load_ext autoreload

[01-26 22:24:39][INFO] 2025-01-26 22:24:39.163001
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Enlace: https://github.com/KennethJYS/Participaci-n-en-clase-11-y-12

# Examen

## Determinante

In [53]:
import numpy as np
from src import (
    eliminacion_gaussiana,
    descomposicion_LU,
    resolver_LU,
    matriz_aumentada,
    separar_m_aumentada,
)


# ####################################################################
def calc_determinante(A: np.ndarray) -> float:
    """Función que calcula el determinante usando el método...
    [Descomposición LU, eliminación gaussiana, Gauss-Jordan, Gauss-Jacobi o Gauss-Seidel]

    ## Parameters
    ``A``: Matriz cuadrada de tamaño n x n

    ## Return
    ``detA``: Determinante de la matriz A

    """

    L, U = descomposicion_LU(A)

    detA = np.prod(np.diag(U))
    return detA


# Ejercicio 1

In [54]:
A1 = [
    [-4, 2, -4, -4, 1, 2, 5, 3, 5, 1],
    [1, 0, 4, 3, 0, -2, 3, 0, 1, 5],
    [5, 5, -4, 5, -4, 2, 2, 2, 4, 4],
    [-1, 3, 4, -1, -4, 0, 5, 0, 0, 5],
    [4, 1, 4, 2, 0, 0, 3, -1, 0, 2],
    [2, -2, 1, -1, -2, -3, 2, -2, 4, -1],
    [3, -2, -3, -2, -1, -3, 5, -1, 5, 0],
    [3, 4, -3, 3, -2, 2, -4, -4, 1, 5],
    [-4, 0, 3, 3, -3, -2, -2, 0, 5, -4],
    [-2, 4, 4, -2, -1, 1, 5, -1, 3, -3],
]
detA1 = calc_determinante(A1)
print(f"Determinante: {detA1}")

[01-26 22:24:39][INFO] 
[[ 5.   5.  -4.   5.  -4.   2.   2.   2.   4.   4. ]
 [ 0.  -1.   4.8  2.   0.8 -2.4  2.6 -0.4  0.2  4.2]
 [ 0.   6.  -7.2  0.  -2.2  3.6  6.6  4.6  8.2  4.2]
 [ 0.   4.   3.2  0.  -4.8  0.4  5.4  0.4  0.8  5.8]
 [ 0.  -3.   7.2 -2.   3.2 -1.6  1.4 -2.6 -3.2 -1.2]
 [ 0.  -4.   2.6 -3.  -0.4 -3.8  1.2 -2.8  2.4 -2.6]
 [ 0.  -5.  -0.6 -5.   1.4 -4.2  3.8 -2.2  2.6 -2.4]
 [ 0.   1.  -0.6  0.   0.4  0.8 -5.2 -5.2 -1.4  2.6]
 [ 0.   4.  -0.2  7.  -6.2 -0.4 -0.4  1.6  8.2 -0.8]
 [ 0.   6.   2.4  0.  -2.6  1.8  5.8 -0.2  4.6 -1.4]]
[01-26 22:24:39][INFO] 
[[ 5.          5.         -4.          5.         -4.          2.
   2.          2.          4.          4.        ]
 [ 0.          6.         -7.2         0.         -2.2         3.6
   6.6         4.6         8.2         4.2       ]
 [ 0.          0.          3.6         2.          0.43333333 -1.8
   3.7         0.36666667  1.56666667  4.9       ]
 [ 0.          0.          8.          0.         -3.33333333 -2.
  

# Ejercicio 2

In [55]:
A2 = [
    [2, 2, 4, 5, -2, -3, 2, -2],
    [-1, -1, 3, 2, 1, 1, -4, 4],
    [2, 5, -3, -3, -2, 2, 5, 3],
    [-2, -4, 0, 1, -1, 5, -4, -1],
    [1, -2, -1, 5, 5, 2, 1, -2],
    [5, 4, 0, 3, 4, -1, -3, -2],
    [4, -4, 1, 2, 3, 3, -1, 3],
    [-2, 1, -3, 0, 5, 4, 4, -4],
]
detA2 = calc_determinante(A2)
print(f"Determinante: {detA2}")

[01-26 22:24:39][INFO] 
[[ 5.   4.   0.   3.   4.  -1.  -3.  -2. ]
 [ 0.  -0.2  3.   2.6  1.8  0.8 -4.6  3.6]
 [ 0.   3.4 -3.  -4.2 -3.6  2.4  6.2  3.8]
 [ 0.  -2.4  0.   2.2  0.6  4.6 -5.2 -1.8]
 [ 0.  -2.8 -1.   4.4  4.2  2.2  1.6 -1.6]
 [ 0.   0.4  4.   3.8 -3.6 -2.6  3.2 -1.2]
 [ 0.  -7.2  1.  -0.4 -0.2  3.8  1.4  4.6]
 [ 0.   2.6 -3.   1.2  6.6  3.6  2.8 -4.8]]
[01-26 22:24:39][INFO] 
[[ 5.          4.          0.          3.          4.         -1.
  -3.         -2.        ]
 [ 0.         -7.2         1.         -0.4        -0.2         3.8
   1.4         4.6       ]
 [ 0.          0.         -2.52777778 -4.38888889 -3.69444444  4.19444444
   6.86111111  5.97222222]
 [ 0.          0.         -0.33333333  2.33333333  0.66666667  3.33333333
  -5.66666667 -3.33333333]
 [ 0.          0.         -1.38888889  4.55555556  4.27777778  0.72222222
   1.05555556 -3.38888889]
 [ 0.          0.          4.05555556  3.77777778 -3.61111111 -2.38888889
   3.27777778 -0.94444444]
 [ 0.          0